version: '3.7'
services:
  neo4j:
    image: neo4j:4.4.7
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
    #change "/Users/lisettek-h/Desktop/PROD_2022031/" to the path where your JSON files are located
      - /Users/lisettek-h/Desktop/PROD_2022031/:/var/lib/neo4j/import
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]
